### PR TITLE
Custom artifact import

### PR DESCRIPTION
**Pull request by abhilash-kumar-nair**
Code to test
Jira - https://modelonproducts.atlassian.net/browse/FLOW-527
```
from modelon.impact.client import Client

client = Client(url="http://localhost:8888/impact", interactive=True)
workspace = client.get_workspace("test")

# Choose analysis type
dynamic = workspace.get_custom_function('dynamic')

# Get model class
model = workspace.get_model("Modelica.Blocks.Examples.PID_Controller")

# Execute experiment
experiment_definition = model.new_experiment_definition(dynamic)
exp = workspace.create_experiment(experiment_definition)
exp = exp.execute().wait()
case = exp.get_case('case_1')
path= "/home/akn/Downloads/Result 2.csv"
ca_import = case.import_custom_artifact(path, "test")
print(ca_import.status)
ca=ca_import.wait()
print(ca.id)
```

### CODE REVIEW

**Comment by iakovn** [comment]
@psundstrom @maraberg  are you OK with the example flow above? 

@abhilash-kumar-nair I suggest we mark the method experimental as we probably need do bump required open api version to enable this feature.

**Comment by abhilash-kumar-nair** [comment]
> @psundstrom @maraberg are you OK with the example flow above?
> 
> @abhilash-kumar-nair I suggest we mark the method experimental as we probably need do bump required open api version to enable this feature.

@iakovn Sure! Done!

**Comment by psundstrom** [comment]
Looks good to me to. Will there be a corresponding .get workflow to find out what custom artifacts there are for a case?

Also I see a risk that you might upload artifacts to old results that you didn't intend to. This is solved if you can mark a case/experiment as finalized and then you can't change it.

**Comment by abhilash-kumar-nair** [comment]
> Looks good to me to. Will there be a corresponding .get workflow to find out what custom artifacts there are for a case?
> 
> Also I see a risk that you might upload artifacts to old results that you didn't intend to. This is solved if you can mark a case/experiment as finalized and then you can't change it.

We already have an api for fetching artifacts for a case?
custom_artifacts = case.get_artifacts()

Hmm what do you mean by Old results? A user will get an error if they try to upload a artifact with ID same as an existing ID unless they specify overwrite.(See the latest commit)

**Comment by psundstrom** [comment]
> > Looks good to me to. Will there be a corresponding .get workflow to find out what custom artifacts there are for a case?
> > Also I see a risk that you might upload artifacts to old results that you didn't intend to. This is solved if you can mark a case/experiment as finalized and then you can't change it.
> 
> We already have an api for fetching artifacts for a case? custom_artifacts = case.get_artifacts()
Lovely!
> 
> Hmm what do you mean by Old results? A user will get an error if they try to upload a artifact with ID same as an existing ID unless they specify overwrite.(See the latest commit)
I meant there's nothing preventing me from adding artifacts to a 2 month old result. But this is a separate topic I think.

**Review by iakovn — APPROVED** [review]
Let's get it in! ✈️

**Pull request merged**
