### PR TITLE
fix: assert compilation is successful before calling download FMU api

### PR DESCRIPTION
**Pull request by abhilash-kumar-nair**
```
from modelon.impact.client import Client

client = Client(url="https://jhmi.modelon.com/", interactive=True,)
workspace = client.get_workspace("test")

# Choose analysis type
dynamic = workspace.get_custom_function('dynamic')

# Get model
model = workspace.get_model("Test.PID_Controller")
compiler_options = dynamic.get_compiler_options().with_values(c_compiler='gcc')
runtime_options = {'cs_solver': 0}
fmu = model.compile(compiler_options, runtime_options).wait()
# Compilation fails
print(fmu.is_successful())
# Output :- False

# Trying to call the download method on the fmu object
fmu_path = fmu.download('/home/jovyan/impact/workspaces/test')
# Raises OperationFailureError: Compilation failed! See the log for more info!

# Cause of failure
log = fmu.get_log()
log.show()
# Output :-
# Error in flattened model:
#     Index reduction failed: There were unmatched equations and/or variables left after index reduction.
# Error in flattened model:
#     The system is structurally singular. The following variable(s) could not be matched to any equation:
#      der(spring.w_rel)
#      torque.flange.phi

#   The following equation(s) could not be matched to any variable:
#     spring.w_rel = der(spring.phi_rel)
#     0.0 = 0.0

```

### CODE REVIEW

**Review by anna-lindholm — APPROVED** [review]
Great additions, thanks Abhilash!

**Review by efredriksson-modelon — CHANGES_REQUESTED** [review]
Nice fix! 👍 I don't think the quick start script has to change, in fact now it would behave as expected.

**Comment by abhilash-kumar-nair** [comment]
> Nice fix! 👍 I don't think the quick start script has to change, in fact now it would behave as expected.

Makes sense! Fixed it! :)

**Review by efredriksson-modelon — APPROVED** [review]
👍

**Pull request merged**
