### PR TITLE
fix: added mapping for python client-MI version compatibility

### PR DESCRIPTION
**Pull request by abhilash-kumar-nair**
https://modelonproducts.atlassian.net/browse/FLOW-24

### CODE REVIEW

**Review by iakovn — CHANGES_REQUESTED** [review]
This will be really helpful! Only comment is to use inexact version spec to avoid any confusion about patch versions.
Other thing I'm unsure about is if we need to separate desktop from cloud version

**Comment by maraberg** [comment]
I like this very much. It would be appreciated if this was reflected here as well: https://modelon-impact-client.readthedocs.io/en/latest/install.html

**Comment by iakovn** [comment]
> I like this very much. It would be appreciated if this was reflected here as well: https://modelon-impact-client.readthedocs.io/en/latest/install.html

@maraberg  This will be published when merged. Or do you mean adding a pointer to this text from the first section?

**Comment by abhilash-kumar-nair** [comment]
Hi @maraberg , @iakovn , Thanks for suggestion! I have now made the suggested fixes. Could you please take another look?

**Comment by maraberg** [comment]
Looks good!

**Review by iakovn — APPROVED** [review]
👍

**Pull request merged**
