### PR TITLE
Upload import

### PR DESCRIPTION
**Pull request by abhilash-kumar-nair**
Renamed newly added methods to use "import_" instead of "upload_". NOTE:- I have not updated the old ones using 'upload' terminology to not do any breaking change.

### CODE REVIEW

**Comment by iakovn** [comment]
@efredriksson-modelon do you remember why original methods were called `upload_*` when it's `import_*` in the REST API and UX?

**Comment by efredriksson-modelon** [comment]
> @efredriksson-modelon do you remember why original methods were called `upload_*` when it's `import_*` in the REST API and UX?

No I can't remember anything, I don't think there was much though put into the word 'upload'.

**Review by efredriksson-modelon — APPROVED** [review]
:+1:

**Review by iakovn — APPROVED** [review]
👍

**Pull request merged**
