### PR TITLE
chore: bump requests package

### PR DESCRIPTION
**Pull request by abhilash-kumar-nair**

### CODE REVIEW

**Review by iakovn — CHANGES_REQUESTED** [review]
It should be "chore" commit as released package requirements are not updated. Or do you think we need to require newer requests in installations?

**Comment by abhilash-kumar-nair** [comment]
@iakovn Semantic bot wont create a release for "chore" I guess? Wanted to bump the python client version in diraction so thought would be good to have the request dependency same as the python client so that I could just do a find and replace in diraction.

**Comment by abhilash-kumar-nair** [comment]
Thanks for the clarification on teams. Fixed it :)

**Review by iakovn — APPROVED** [review]
👍

**Pull request merged**
