### PR TITLE
feat: added support for result import to case behind experimental flag

### PR DESCRIPTION
**Pull request by abhilash-kumar-nair**
**Jira** - https://modelonproducts.atlassian.net/browse/FLOW-523

**Code to test**

```
import os
os.environ["IMPACT_PYTHON_CLIENT_EXPERIMENTAL"] = "1"
from modelon.impact.client import Client

client = Client(url="http://localhost:8888/impact", interactive=True)
workspace = client.get_workspace("test")

# Choose analysis type
dynamic = workspace.get_custom_function('dynamic')

# Get model class
model = workspace.get_model("Modelica.Blocks.Examples.PID_Controller")

# Execute experiment
experiment_definition = model.new_experiment_definition(dynamic)
exp = workspace.execute(experiment_definition).wait()
case_1 = exp.get_case('case_1')
result = case_1.import_result('/home/akn/Downloads/Result.csv', overwrite=True).wait()
print(result.keys())
```

### CODE REVIEW

**Comment by maraberg** [comment]
I think the script looks a bit weird - aren't we supposed to use "empty" cf in order for result upload to be valid?

**Comment by iakovn** [comment]
> I think the script looks a bit weird - aren't we supposed to use "empty" cf in order for result upload to be valid?

We moved back to using (any) actual custom functions and not empty. If your only intention is to load results you can create a custom function "load_results" in the library.

**Comment by maraberg** [comment]
Minor thing: Do we do any checks on the backend on the csv data types, I managed to upload a csv - file with semi-colons as dividers: this was the result:
image

**Comment by maraberg** [comment]
For multi-case simulation it seems like the result.keys() are not correct:
image

**Comment by maraberg** [comment]
Same with trajectory object:

image

**Comment by maraberg** [comment]
[sandbox.zip](https://github.com/user-attachments/files/15901651/sandbox.zip)

Zip with resources used for tests

**Comment by maraberg** [comment]
I have not looked at the code changes - let me know if you think this is valuable, I don't think so myself :)

**Comment by abhilash-kumar-nair** [comment]
> Minor thing: Do we do any checks on the backend on the csv data types, I managed to upload a csv - file with semi-colons as dividers: this was the result: image

Good catch. I will add checks for delimiter and raise appropriate errors while validating such results

**Comment by abhilash-kumar-nair** [comment]
> ny checks on the backend on the csv data types, I managed to upload a csv - file with semi-colons as dividers: this was the result:

We would need another api to fetch CaseResult variables. Currently we only have one that operates on the experiment level. This was your concern right?

The current GET /variables api seems to correctly capture the variables in your simulated result file and the overwritten result file.

**Comment by abhilash-kumar-nair** [comment]
> > Minor thing: Do we do any checks on the backend on the csv data types, I managed to upload a csv - file with semi-colons as dividers: this was the result: image
> 
> Good catch. I will add checks for delimiter and raise appropriate errors while validating such results

Thanks a lot for the user feedback @maraberg ! I will work on making the changes you suggested and get back to you for another round of testing :)

**Pull request merged**
