### PR TITLE
fix: corrected query string for get_projects api

### PR DESCRIPTION
**Pull request by abhilash-kumar-nair**

### CODE REVIEW

**Review by iakovn — CHANGES_REQUESTED** [review]
Could you add a test for this?
On a related topic - have you reviewed test coverage recently? We might have missed some other  minor things as well.

**Comment by abhilash-kumar-nair** [comment]
> Could you add a test for this? On a related topic - have you reviewed test coverage recently? We might have missed some other minor things as well.

Unfortunately we couldn't have caught this one with unit test.. Need integration tests to catch such things since the filtering is done by the server. I can add a integration test. Here's the latest test coverage report - https://jenkins.modelon.com/internal/job/WAMSTeam/job/impact-client-python/job/project-type-fix/1/Test_20coverage_20report/. Its at 90 % but could be improved. :)

**Comment by abhilash-kumar-nair** [comment]
> > Could you add a test for this? On a related topic - have you reviewed test coverage recently? We might have missed some other minor things as well.
> 
> Unfortunately we couldn't have caught this one with unit test.. Need integration tests to catch such things since the filtering is done by the server. I can add a integration test. Here's the latest test coverage report - https://jenkins.modelon.com/internal/job/WAMSTeam/job/impact-client-python/job/project-type-fix/1/Test_20coverage_20report/. Its at 90 % but could be improved. :)

Ah sorry you meant adding a test with a query parameter and checking if the query parameter was sent correctly? That can be done!

**Review by iakovn — APPROVED** [review]
👍

**Pull request merged**
